//
//  ItemRouter.swift
//  KinoPub
//
//  Created by Maksim Kolesnik on 07/03/2020.
//  Copyright (c) 2020 Maksim Kolesnik. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

public final class ItemRouter {
    public weak var output: ItemRouterOutput?
    public weak var viewController: UIViewController?

}

extension ItemRouter: ItemRouterInput {
    public func didSelect(model: Season) {
        do {
            try Transition(source: viewController)
                .openModule(using: SeasonFactory(), with: { (source, destination) in
                    source.navigationController?.pushViewController(destination, animated: true)
                })
                .perform(moduleInput: { (presenter) in
                    presenter.setupWith(model)
                })
        } catch {
            print(error)
        }
    }

}
