//
//  ItemFactory.swift
//  KinoPub
//
//  Created by Maksim Kolesnik on 07/03/2020.
//  Copyright (c) 2020 Maksim Kolesnik. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

public final class ItemFactory: TransitionFactory {
    public typealias ModuleInputType = ItemPresenterInput
    public typealias ViewType = ItemViewController

    private let networkService: NetworkServiceFactory
    public init() {
        let keyValueStorage = KeyChainStorageFactory()
        let accessTokenService = DefaultAccessTokenServiceFactory(keyValueStorage: keyValueStorage)
        self.networkService = MoyaNetworkServiceFactory(accessTokenService: accessTokenService)
    }
    public func instantiateModuleTransitionHandler() -> ViewType {
        let interactor = ItemInteractor(networkService: networkService)
        let router = ItemRouter()
        let presenter = ItemPresenter(interactor: interactor, router: router)
    	let viewController = ViewType(presenter: presenter)

        presenter.view = viewController
        interactor.output = presenter
        router.output = presenter
        router.viewController = viewController
        return viewController
    }

}
