//
//  BookmarksModule.swift
//  KinoPub
//
//  Created by Maksim Kolesnik on 06/03/2020.
//  Copyright (c) 2020 Maksim Kolesnik. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import Combine

// MARK: - Interactor

public protocol BookmarksInteractorInput: AnyObject {
    func interact()
    func requestBookmarks() -> AnyPublisher<[Bookmark], Never>

}

public protocol BookmarksInteractorOutput: AnyObject {

}

// MARK: - Presenter

public protocol BookmarksPresenterInput: AnyObject {

}

public protocol BookmarksPresenterOutput: AnyObject {
    func setupInitialState()
}

// MARK: - Router

public protocol BookmarksRouterInput: AnyObject {
    func didSelect(model: Bookmark)
}

public protocol BookmarksRouterOutput: AnyObject {

}

// MARK: - View

public protocol BookmarksViewInput: AnyObject {

}

public protocol BookmarksViewOutput: AnyObject {
    func didTriggerViewReadyEvent()
    func requestBookmarks() -> AnyPublisher<[Bookmark], Never>
    func didSelect(model: Bookmark)
}
