//
//  BookmarksViewController.swift
//  KinoPub
//
//  Created by Maksim Kolesnik on 06/03/2020.
//  Copyright (c) 2020 Maksim Kolesnik. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import DTTableViewManager
import DTModelStorage
import Combine

public final class BookmarksViewController: UIViewController, TransitionView {

    // MARK: - Private
    private var subscriptions = Set<AnyCancellable>()

    fileprivate lazy var _tableView: UITableView = {
        let tableView = UITableView(frame: .zero, style: .grouped)
        tableView.delegate = self
        return tableView
    }()

    public let presenter: BookmarksViewOutput
    public init(presenter: BookmarksViewOutput) {
        self.presenter = presenter
        super.init(nibName: nil, bundle: nil)
    }

    public required init?(coder: NSCoder) { fatalError("init(coder:) has not been implemented") }

    // MARK: - Lifecycle

    public override func viewDidLoad() {
        super.viewDidLoad()
        presenter.didTriggerViewReadyEvent()
    }

    private func setupContent() {
        view.addSubview(tableView)
        self.title = "Избранное"
    }

    private func setupLayout() {
        tableView.translatesAutoresizingMaskIntoConstraints = false
        tableView.leadingAnchor.constraint(equalTo: view.leadingAnchor).isActive = true
        tableView.trailingAnchor.constraint(equalTo: view.trailingAnchor).isActive = true
        tableView.bottomAnchor.constraint(equalTo: view.bottomAnchor).isActive = true
        tableView.topAnchor.constraint(equalTo: view.topAnchor).isActive = true
    }
}

// MARK: - BookmarksViewInput

extension BookmarksViewController: BookmarksViewInput {

}

// MARK: - BookmarksPresenterOutput

extension BookmarksViewController: BookmarksPresenterOutput {
    public func setupInitialState() {
        setupContent()
        setupLayout()

        presenter.requestBookmarks()
            .subscribe(manager.memoryStorage.recive())

        manager.register(TableViewCell.self)
        manager.didSelect(TableViewCell.self, { [weak self] (_, model, _) in
            self?.presenter.didSelect(model: model)
        })
    }

}

extension BookmarksViewController: DTTableViewManageable {
    public var tableView: UITableView! {
        return _tableView
    }
}

extension BookmarksViewController: UITableViewDelegate {

    public func tableView(_ tableView: UITableView, heightForHeaderInSection section: Int) -> CGFloat {
        return 35
    }

    public func tableView(_ tableView: UITableView, didSelectRowAt indexPath: IndexPath) {
        tableView.deselectRow(at: indexPath, animated: true)
    }
}

extension BookmarksViewController {
    public final class TableViewCell: UITableViewCell, ModelTransfer {
        public override init(style: UITableViewCell.CellStyle, reuseIdentifier: String?) {
            super.init(style: UITableViewCell.CellStyle.value1, reuseIdentifier: reuseIdentifier)
            self.accessoryType = .disclosureIndicator
        }

        public required init?(coder: NSCoder) { fatalError("init(coder:) has not been implemented") }

        public func update(with model: Bookmark) {
            self.textLabel?.text = model.title
            self.detailTextLabel?.text = "\(model.count)"
        }
    }
}
