//
//  BookmarksFactory.swift
//  KinoPub
//
//  Created by Maksim Kolesnik on 06/03/2020.
//  Copyright (c) 2020 Maksim Kolesnik. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

public final class BookmarksFactory: TransitionFactory {

    public typealias ModuleInputType = BookmarksPresenterInput
    public typealias ViewType = BookmarksViewController

    private let networkService: NetworkServiceFactory
    public init() {
        let keyValueStorage = KeyChainStorageFactory()
        let accessTokenService = DefaultAccessTokenServiceFactory(keyValueStorage: keyValueStorage)
        let moyaNetworkService = MoyaNetworkServiceFactory(accessTokenService: accessTokenService)
        let authorizationService = DefaultAuthorizationServiceFactory(networkService: moyaNetworkService,
                                                                      accessTokenService: accessTokenService)
        let errorHandling = ErrorHandlingNetworkServiceFactory(networkService: moyaNetworkService,
                                                               authorizationService: authorizationService)
        self.networkService = errorHandling
    }

    public func instantiateModuleTransitionHandler() -> ViewType {
        let interactor = BookmarksInteractor(networkService: networkService)
        let router = BookmarksRouter()
        let presenter = BookmarksPresenter(interactor: interactor, router: router)
    	let viewController = ViewType(presenter: presenter)

        presenter.view = viewController
        interactor.output = presenter
        router.output = presenter
        router.viewController = viewController
        return viewController
    }

}
