//
//  SeasonRouter.swift
//  KinoPub
//
//  Created by Maksim Kolesnik on 07/03/2020.
//  Copyright (c) 2020 Maksim Kolesnik. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

public final class SeasonRouter {
    public weak var output: SeasonRouterOutput?
    public weak var viewController: UIViewController?

}

extension SeasonRouter: SeasonRouterInput {

}
