//
//  SeasonFactory.swift
//  KinoPub
//
//  Created by Maksim Kolesnik on 07/03/2020.
//  Copyright (c) 2020 Maksim Kolesnik. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

public final class SeasonFactory: TransitionFactory {
    public typealias ModuleInputType = SeasonPresenterInput
    public typealias ViewType = SeasonViewController

    public func instantiateModuleTransitionHandler() -> ViewType {
        let keyValueStorage = KeyChainStorageFactory()
        let accessTokenService = DefaultAccessTokenServiceFactory(keyValueStorage: keyValueStorage)
        let moyaNetworkService = MoyaNetworkServiceFactory(accessTokenService: accessTokenService)
        let interactor = SeasonInteractor(downloadService: AlamofireDownloadServiceFactory(),
                                          networkService: moyaNetworkService)
        let router = SeasonRouter()
        let presenter = SeasonPresenter(interactor: interactor, router: router)
    	let viewController = ViewType(presenter: presenter)

        presenter.view = viewController
        interactor.output = presenter
        router.output = presenter
        router.viewController = viewController
        return viewController
    }

}
