//
//  BookmarkRouter.swift
//  KinoPub
//
//  Created by Maksim Kolesnik on 07/03/2020.
//  Copyright (c) 2020 Maksim Kolesnik. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

public final class BookmarkRouter {
    public weak var output: BookmarkRouterOutput?
    public weak var viewController: UIViewController?

}

extension BookmarkRouter: BookmarkRouterInput {
    public func didSelect(model: Bookmark.Item) {
        do {
            try Transition(source: viewController)
                .openModule(using: ItemFactory(), with: { (source, destination) in
                    source.navigationController?.pushViewController(destination, animated: true)
                })
                .perform(moduleInput: { (presenter) in
                    presenter.setupWith(model)
                })
        } catch {
            print(error)
        }
    }
}
